// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "AHRS.h"
#include "WPILib.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::subsystemDrivetreadLeftFront;
std::shared_ptr<SpeedController> RobotMap::subsystemDrivetreadLeftBack;
std::shared_ptr<SpeedController> RobotMap::subsystemDrivetreadRightBack;
std::shared_ptr<SpeedController> RobotMap::subsystemDrivetreadRightFront;
std::shared_ptr<RobotDrive> RobotMap::subsystemDriveRobotDrive41;
//static std::shared_ptr<RobotDrive> subsystemDriveRobotDrive41;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
AHRS *RobotMap::ahrs;
Solenoid *RobotMap::ClaspSolenoid;//module 0 channel 0
Solenoid *RobotMap::ArmSolenoid;//module 0 channel 1Talon
Solenoid *RobotMap::SpeedSolenoid;
Joystick *RobotMap::buttonBoard;
CANTalon *RobotMap::cantalonLeftFront;
CANTalon *RobotMap::cantalonLeftBack;
CANTalon *RobotMap::cantalonRightBack;
CANTalon *RobotMap::cantalonRightFront;

DigitalInput *RobotMap::digitalInput0;
DigitalInput *RobotMap::digitalInput1;
DigitalInput *RobotMap::digitalInput2;


void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

  /*  subsystemDrivetreadLeftFront.reset(new Talon(1));
    subsystemDrivetreadLeftBack.reset(new Talon(0));
    subsystemDrivetreadRightBack.reset(new Talon(2));
    subsystemDrivetreadRightFront.reset(new Talon(3));
    lw->AddActuator("SubsystemDrive", "treadLeftFront", std::static_pointer_cast<Talon>(subsystemDrivetreadLeftFront));
    lw->AddActuator("SubsystemDrive", "treadLeftBack", std::static_pointer_cast<Talon>(subsystemDrivetreadLeftBack));
    lw->AddActuator("SubsystemDrive", "treadRightBack", std::static_pointer_cast<Talon>(subsystemDrivetreadRightBack));
    lw->AddActuator("SubsystemDrive", "treadRightFront", std::static_pointer_cast<Talon>(subsystemDrivetreadRightFront));
    subsystemDriveRobotDrive41.reset(new RobotDrive(subsystemDrivetreadLeftFront, subsystemDrivetreadLeftBack,
              subsystemDrivetreadRightFront, subsystemDrivetreadRightBack));
*/

    cantalonLeftFront=new CANTalon(1);
    cantalonLeftBack=new CANTalon(2);
    cantalonRightBack=new CANTalon(4);
    cantalonRightFront=new CANTalon(3);
    cantalonLeftBack->SetControlMode(CANTalon::kFollower);
    cantalonLeftBack->Set(1);

    cantalonRightBack->SetControlMode(CANTalon::kFollower);
    cantalonRightBack->Set(3);

    cantalonLeftFront->SetInverted(true);
    cantalonLeftBack->SetInverted(true);
    cantalonRightBack->SetInverted(true);
    cantalonRightFront->SetInverted(true);

    subsystemDriveRobotDrive41.reset(new RobotDrive(cantalonLeftFront,cantalonRightFront));
    lw->AddActuator("SubsystemDrive", "treadLeftFront", cantalonLeftFront);
    lw->AddActuator("SubsystemDrive", "treadLeftBack", cantalonLeftBack);
    lw->AddActuator("SubsystemDrive", "treadRightBack", cantalonRightBack);
    lw->AddActuator("SubsystemDrive", "treadRightFront", cantalonRightFront);

    cantalonLeftFront->SetFeedbackDevice(CANTalon::FeedbackDevice::QuadEncoder );
    cantalonLeftFront->ConfigEncoderCodesPerRev(360);
    double position = 0;
    //cantalonLeftFront->SetPosition(position);
    cantalonLeftFront->SetEncPosition(0);
    //cantalonLeftFront->ConfigForwardLimit(15);
    //cantalonLeftFront->ConfigReverseLimit(-15);



    
    subsystemDriveRobotDrive41->SetSafetyEnabled(false);
        subsystemDriveRobotDrive41->SetExpiration(0.1);
        subsystemDriveRobotDrive41->SetSensitivity(0.5);
        subsystemDriveRobotDrive41->SetMaxOutput(1.0);

    try {
    			/***********************************************************************
    			 * navX-MXP:
    			 * - Communication via RoboRIO MXP (SPI, I2C, TTL UART) and USB.
    			 * - See http://navx-mxp.kauailabs.com/guidance/selecting-an-interface.
    			 *
    			 * navX-Micro:
    			 * - Communication via I2C (RoboRIO MXP or Onboard) and USB.
    			 * - See http://navx-micro.kauailabs.com/guidance/selecting-an-interface.
    			 *
    			 * Multiple navX-model devices on a single robot are supported.
    			 ************************************************************************/
                ahrs = new AHRS(SPI::Port::kMXP);
            } catch (std::exception& ex ) {
                std::string err_string = "Error instantiating navX MXP:  ";
                err_string += ex.what();
                DriverStation::ReportError(err_string.c_str());
            }
            if ( ahrs ) {
                LiveWindow::GetInstance()->AddSensor("IMU", "Gyro", ahrs);
            }

    ClaspSolenoid = new Solenoid(0,0);  //default set all solenoids to false
    ArmSolenoid = new Solenoid(0, 1);
    SpeedSolenoid = new Solenoid(0, 2);

    buttonBoard = new ButtonBoard(1);
    buttonBoard->SetOutput(3, false);
    buttonBoard->SetOutput(4, false);
    buttonBoard->SetOutput(5, false);
    buttonBoard->SetOutput(9, false);
    buttonBoard->SetOutput(10, false);
    buttonBoard->SetOutput(11, false);

    digitalInput0=new DigitalInput(0);
    digitalInput1=new DigitalInput(1);
    digitalInput2=new DigitalInput(2);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
